export const URL = 'http://localhost:3000';
export const STARTCARDS = [
    {
        "id": "ceo",
        "name": "CEO",
        "price": 1000,
        "profitPerHour": 100,
        "condition": null,
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 100,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 1000,
        "startCurrentProfitPerHour": 100,
        "startPos": 0,
        "value": 10
    },
    {
        "id": "marketing",
        "name": "Marketing",
        "price": 1000,
        "profitPerHour": 70,
        "condition": null,
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 70,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 1000,
        "startCurrentProfitPerHour": 70,
        "startPos": 1,
        "value": 14.285714285714286
    },
    {
        "id": "it_team",
        "name": "IT team",
        "price": 2000,
        "profitPerHour": 240,
        "condition": null,
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 240,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 2000,
        "startCurrentProfitPerHour": 240,
        "startPos": 2,
        "value": 8.333333333333334
    },
    {
        "id": "support_team",
        "name": "Support team",
        "price": 750,
        "profitPerHour": 70,
        "condition": null,
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 70,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 750,
        "startCurrentProfitPerHour": 70,
        "startPos": 3,
        "value": 10.714285714285714
    },
    {
        "id": "facebook_ads",
        "name": "HamsterBook",
        "price": 500,
        "image": 'facebook_ads.svg',
        "profitPerHour": 70,
        "condition": null,
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 70,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 500,
        "startCurrentProfitPerHour": 70,
        "startPos": 4,
        "value": 7.142857142857143
    },
    {
        "id": "youtube",
        "name": "HamsterTube",
        "price": 600,
        "profitPerHour": 90,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "facebook_ads",
            "level": 5
        },
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 90,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 600,
        "startCurrentProfitPerHour": 90,
        "startPos": 5,
        "value": 6.666666666666667
    },
    {
        "id": "x",
        "name": "X",
        "price": 550,
        "image": "x.svg",
        "profitPerHour": 80,
        "condition": null,
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 80,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 550,
        "startCurrentProfitPerHour": 80,
        "startPos": 6,
        "value": 6.875
    },
    {
        "id": "medium",
        "name": "Cointelegraph",
        "price": 350,
        "image": "Cointelegraph.svg",
        "profitPerHour": 40,
        "condition": null,
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 40,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 350,
        "startCurrentProfitPerHour": 40,
        "startPos": 7,
        "value": 8.75
    },
    {
        "id": "instagram",
        "name": "HamsterGram",
        "price": 500,
        "image": "HamsterGram.svg",
        "profitPerHour": 50,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "youtube",
            "level": 8
        },
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 50,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 500,
        "startCurrentProfitPerHour": 50,
        "startPos": 8,
        "value": 10
    },
    {
        "id": "tiktok",
        "name": "TikTok",
        "price": 750,
        "image": "TikTok.svg",
        "profitPerHour": 100,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "instagram",
            "level": 3
        },
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 100,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 750,
        "startCurrentProfitPerHour": 100,
        "startPos": 9,
        "value": 7.5
    },
    {
        "id": "reddit",
        "name": "Сoindesk",
        "price": 1000,
        "image": "Сoindesk.svg",
        "profitPerHour": 80,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "medium",
            "level": 10
        },
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 80,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 1000,
        "startCurrentProfitPerHour": 80,
        "startPos": 10,
        "value": 12.5
    },
    {
        "id": "influencers",
        "name": "Influencers",
        "price": 2500,
        "image": "Influencers.svg",
        "profitPerHour": 270,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "x",
            "level": 5
        },
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 270,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 2500,
        "startCurrentProfitPerHour": 270,
        "startPos": 11,
        "value": 9.25925925925926
    },
    {
        "id": "partnership_program",
        "name": "Partnership program",
        "price": 500,
        "image": "partnership_program.svg",
        "profitPerHour": 70,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "influencers",
            "level": 7
        },
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 70,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 500,
        "startCurrentProfitPerHour": 70,
        "startPos": 12,
        "value": 7.142857142857143
    },
    {
        "id": "product_team",
        "name": "Product team",
        "price": 1000,
        "image": "product_team.svg",
        "profitPerHour": 100,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "ceo",
            "level": 2
        },
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 100,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 1000,
        "startCurrentProfitPerHour": 100,
        "startPos": 13,
        "value": 10
    },
    {
        "id": "bisdev_team",
        "name": "BisDev team",
        "price": 500,
        "image": "bisdev_team.svg",
        "profitPerHour": 50,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "marketing",
            "level": 2
        },
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 50,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 500,
        "startCurrentProfitPerHour": 50,
        "startPos": 14,
        "value": 10
    },
    {
        "id": "two_factor_authentication",
        "name": "Two factor authentication",
        "price": 1000,
        "image": "two_factor_authentication.svg",
        "profitPerHour": 125,
        "condition": {
            "_type": "MoreReferralsCount",
            "moreReferralsCount": 1
        },
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 125,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 1000,
        "startCurrentProfitPerHour": 125,
        "startPos": 15,
        "value": 8
    },
    {
        "id": "ux_ui_team",
        "name": "UX and UI team",
        "price": 760,
        "profitPerHour": 175,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "ceo",
            "level": 5
        },
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 175,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 760,
        "startCurrentProfitPerHour": 175,
        "startPos": 16,
        "value": 4.3428571428571425
    },
    {
        "id": "security_team",
        "name": "Security team",
        "price": 1000,
        "profitPerHour": 200,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "two_factor_authentication",
            "level": 13
        },
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 200,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 1000,
        "startCurrentProfitPerHour": 200,
        "startPos": 17,
        "value": 5
    },
    {
        "id": "qa_team",
        "name": "QA team",
        "price": 1275,
        "profitPerHour": 190,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "it_team",
            "level": 3
        },
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 190,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 1275,
        "startCurrentProfitPerHour": 190,
        "startPos": 18,
        "value": 6.7105263157894735
    },
    {
        "id": "antihacking_shield",
        "name": "Antihacking shield",
        "price": 2000,
        "profitPerHour": 110,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "qa_team",
            "level": 5
        },
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 110,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 2000,
        "startCurrentProfitPerHour": 110,
        "startPos": 19,
        "value": 18.181818181818183
    },
    {
        "id": "risk_management_team",
        "name": "Risk management team",
        "price": 2000,
        "profitPerHour": 265,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "ceo",
            "level": 8
        },
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 265,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 2000,
        "startCurrentProfitPerHour": 265,
        "startPos": 20,
        "value": 7.547169811320755
    },
    {
        "id": "security_audition",
        "name": "Security Audition",
        "price": 3000,
        "profitPerHour": 100,
        "condition": null,
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 100,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 3000,
        "startCurrentProfitPerHour": 100,
        "startPos": 21,
        "value": 30
    },
    {
        "id": "anonymous_transactions_ban",
        "name": "Anonymous transactions ban",
        "price": 900,
        "profitPerHour": 300,
        "condition": {
            "_type": "MoreReferralsCount",
            "moreReferralsCount": 1
        },
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 300,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 900,
        "startCurrentProfitPerHour": 300,
        "startPos": 22,
        "value": 3
    },
    {
        "id": "blocking_suspicious_accounts",
        "name": "Blocking suspicious accounts",
        "price": 1250,
        "profitPerHour": 160,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "anonymous_transactions_ban",
            "level": 7
        },
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 160,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 1250,
        "startCurrentProfitPerHour": 160,
        "startPos": 23,
        "value": 7.8125
    },
    {
        "id": "tokenomics_expert",
        "name": "Tokenomics expert",
        "price": 5000,
        "profitPerHour": 500,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "bisdev_team",
            "level": 3
        },
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 500,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 5000,
        "startCurrentProfitPerHour": 500,
        "startPos": 24,
        "value": 10
    },
    {
        "id": "consensys_explorer_pass",
        "name": "Consensus Explorer pass",
        "price": 25000,
        "profitPerHour": 1500,
        "condition": null,
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 1500,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 25000,
        "startCurrentProfitPerHour": 1500,
        "startPos": 25,
        "value": 16.666666666666668
    },
    {
        "id": "vc_labs",
        "name": "VC Labs",
        "price": 15500,
        "profitPerHour": 500,
        "condition": null,
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 500,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 15500,
        "startCurrentProfitPerHour": 500,
        "startPos": 26,
        "value": 31
    },
    {
        "id": "compliance_officer",
        "name": "Compliance officer",
        "price": 3500,
        "profitPerHour": 120,
        "condition": null,
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 120,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 3500,
        "startCurrentProfitPerHour": 120,
        "startPos": 27,
        "value": 29.166666666666668
    },
    {
        "id": "money_20_20",
        "name": "Welcome to Amsterdam",
        "price": 3000,
        "profitPerHour": 325,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "usdt_on_ton",
            "level": 3
        },
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 325,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 3000,
        "startCurrentProfitPerHour": 325,
        "startPos": 28,
        "value": 9.23076923076923
    },
    {
        "id": "development_hub_mumbai",
        "name": "Development Hub Mumbai",
        "releaseAt": "2024-07-02T11:00:00.000Z",
        "price": 90000,
        "profitPerHour": 4000,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "it_team",
            "level": 15
        },
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 4000,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 90000,
        "startCurrentProfitPerHour": 4000,
        "startPos": 29,
        "value": 22.5
    },
    {
        "id": "data_center_tokyo",
        "name": "Data Сenter Tokyo",
        "releaseAt": "2024-07-05T11:00:00.000Z",
        "price": 200000,
        "profitPerHour": 6500,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "dubai_office",
            "level": 1
        },
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 6500,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 200000,
        "startCurrentProfitPerHour": 6500,
        "startPos": 30,
        "value": 30.76923076923077
    },
    {
        "id": "leaderboards",
        "name": "Leaderboards",
        "releaseAt": "2024-07-07T11:00:00.000Z",
        "price": 20000,
        "profitPerHour": 750,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "kyc",
            "level": 15
        },
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 750,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 20000,
        "startCurrentProfitPerHour": 750,
        "startPos": 31,
        "value": 26.666666666666668
    },
    {
        "id": "mini_game",
        "name": "Minigame",
        "releaseAt": "2024-07-23T11:00:00.000Z",
        "price": 40000,
        "profitPerHour": 1000,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "gamefi_tokens",
            "level": 17
        },
        "section": "PR&Team",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 1000,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 40000,
        "startCurrentProfitPerHour": 1000,
        "startPos": 32,
        "value": 40
    },
    {
        "id": "fan_tokens",
        "name": "Fan tokens",
        "price": 10000,
        "profitPerHour": 950,
        "condition": null,
        "section": "Markets",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 950,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 10000,
        "startCurrentProfitPerHour": 950,
        "startPos": 33,
        "value": 10.526315789473685
    },
    {
        "id": "staking",
        "name": "Staking",
        "price": 3500,
        "image": "Staking.svg",
        "profitPerHour": 600,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "kyc",
            "level": 7
        },
        "section": "Markets",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 600,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 3500,
        "startCurrentProfitPerHour": 600,
        "startPos": 34,
        "value": 5.833333333333333
    },
    {
        "id": "btc_pairs",
        "name": "BTC pairs",
        "price": 250,
        "image": "btc_pairs.svg",
        "profitPerHour": 40,
        "condition": null,
        "section": "Markets",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 40,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 250,
        "startCurrentProfitPerHour": 40,
        "startPos": 35,
        "value": 6.25
    },
    {
        "id": "eth_pairs",
        "name": "ETH pairs",
        "price": 300,
        "image": "eth_pairs.svg",
        "profitPerHour": 40,
        "condition": null,
        "section": "Markets",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 40,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 300,
        "startCurrentProfitPerHour": 40,
        "startPos": 36,
        "value": 7.5
    },
    {
        "id": "top_10_cmc_pairs",
        "name": "Top 10 cmc pairs",
        "price": 1000,
        "image": "top_10_cmc_pairs.svg",
        "profitPerHour": 80,
        "condition": null,
        "section": "Markets",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 80,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 1000,
        "startCurrentProfitPerHour": 80,
        "startPos": 37,
        "value": 12.5
    },
    {
        "id": "gamefi_tokens",
        "name": "GameFi tokens",
        "price": 500,
        "image": "gamefi_tokens.svg",
        "profitPerHour": 70,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "youtube",
            "level": 4
        },
        "section": "Markets",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 70,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 500,
        "startCurrentProfitPerHour": 70,
        "startPos": 38,
        "value": 7.142857142857143
    },
    {
        "id": "defi2.0_tokens",
        "name": "Defi2.0 tokens",
        "price": 500,
        "image": "defi.svg",
        "profitPerHour": 40,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "ceo",
            "level": 2
        },
        "section": "Markets",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 40,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 500,
        "startCurrentProfitPerHour": 40,
        "startPos": 39,
        "value": 12.5
    },
    {
        "id": "socialfi_tokens",
        "name": "SocialFi tokens",
        "price": 500,
        "image": "socialfi_tokens.svg",
        "profitPerHour": 50,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "gamefi_tokens",
            "level": 11
        },
        "section": "Markets",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 50,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 500,
        "startCurrentProfitPerHour": 50,
        "startPos": 40,
        "value": 10
    },
    {
        "id": "meme_coins",
        "name": "Meme coins",
        "price": 2000,
        "profitPerHour": 110,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "influencers",
            "level": 10
        },
        "section": "Markets",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 110,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 2000,
        "startCurrentProfitPerHour": 110,
        "startPos": 41,
        "value": 18.181818181818183
    },
    {
        "id": "shit_coins",
        "name": "Shit coins",
        "price": 5000,
        "image": "shit_coins.svg",
        "profitPerHour": 590,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "kyb",
            "level": 3
        },
        "section": "Markets",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 590,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 5000,
        "startCurrentProfitPerHour": 590,
        "startPos": 42,
        "value": 8.474576271186441
    },
    {
        "id": "margin_trading_x10",
        "name": "Margin trading x10",
        "price": 2500,
        "image": "margin_trading_x10.svg",
        "profitPerHour": 275,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "shit_coins",
            "level": 5
        },
        "section": "Markets",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 275,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 2500,
        "startCurrentProfitPerHour": 275,
        "startPos": 43,
        "value": 9.090909090909092
    },
    {
        "id": "margin_trading_x20",
        "name": "Margin trading x20",
        "price": 2500,
        "image": "margin_trading_x20.svg",
        "profitPerHour": 350,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "margin_trading_x10",
            "level": 5
        },
        "section": "Markets",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 350,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 2500,
        "startCurrentProfitPerHour": 350,
        "startPos": 44,
        "value": 7.142857142857143
    },
    {
        "id": "margin_trading_x30",
        "name": "Margin trading x30",
        "price": 3500,
        "image": "margin_trading_x30.svg",
        "profitPerHour": 500,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "legal_opinion",
            "level": 6
        },
        "section": "Markets",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 500,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 3500,
        "startCurrentProfitPerHour": 500,
        "startPos": 45,
        "value": 7
    },
    {
        "id": "margin_trading_x50",
        "name": "Margin trading x50",
        "price": 10000,
        "image": "margin_trading_x50.svg",
        "profitPerHour": 1100,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "margin_trading_x30",
            "level": 8
        },
        "section": "Markets",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 1100,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 10000,
        "startCurrentProfitPerHour": 1100,
        "startPos": 46,
        "value": 9.090909090909092
    },
    {
        "id": "margin_trading_x75",
        "name": "Margin trading x75",
        "price": 7500,
        "image": "margin_trading_x75.svg",
        "profitPerHour": 1100,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "short_squeeze",
            "level": 10
        },
        "section": "Markets",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 1100,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 7500,
        "startCurrentProfitPerHour": 1100,
        "startPos": 47,
        "value": 6.818181818181818
    },
    {
        "id": "margin_trading_x100",
        "name": "Margin trading x100",
        "price": 5000,
        "image": "margin_trading_x100.svg",
        "profitPerHour": 975,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "short_squeeze",
            "level": 3
        },
        "section": "Markets",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 975,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 5000,
        "startCurrentProfitPerHour": 975,
        "startPos": 48,
        "value": 5.128205128205129
    },
    {
        "id": "derivatives",
        "name": "Derivatives",
        "price": 2500,
        "image": "derivatives.svg",
        "profitPerHour": 495,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "margin_trading_x20",
            "level": 9
        },
        "section": "Markets",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 495,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 2500,
        "startCurrentProfitPerHour": 495,
        "startPos": 49,
        "value": 5.05050505050505
    },
    {
        "id": "prediction_markets",
        "name": "Prediction markets",
        "price": 1750,
        "image": "prediction_markets.svg",
        "profitPerHour": 345,
        "condition": {
            "_type": "ReferralCount",
            "referralCount": 2
        },
        "section": "Markets",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 345,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 1750,
        "startCurrentProfitPerHour": 345,
        "startPos": 50,
        "value": 5.072463768115942
    },
    {
        "id": "web3_integration",
        "name": "Web3 integration",
        "price": 6500,
        "image": "web3_integration.svg",
        "profitPerHour": 790,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "anti_money_loundering",
            "level": 8
        },
        "section": "Markets",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 790,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 6500,
        "startCurrentProfitPerHour": 790,
        "startPos": 51,
        "value": 8.227848101265822
    },
    {
        "id": "dao",
        "name": "DAO",
        "price": 1000,
        "profitPerHour": 230,
        "condition": {
            "_type": "ReferralCount",
            "referralCount": 4
        },
        "section": "Markets",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 230,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 1000,
        "startCurrentProfitPerHour": 230,
        "startPos": 52,
        "value": 4.3478260869565215
    },
    {
        "id": "p2p_trading",
        "name": "P2P trading",
        "price": 4200,
        "profitPerHour": 390,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "kyc",
            "level": 7
        },
        "section": "Markets",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 390,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 4200,
        "startCurrentProfitPerHour": 390,
        "startPos": 53,
        "value": 10.76923076923077
    },
    {
        "id": "trading_bots",
        "name": "Trading bots",
        "price": 2100,
        "profitPerHour": 195,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "it_team",
            "level": 9
        },
        "section": "Markets",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 195,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 2100,
        "startCurrentProfitPerHour": 195,
        "startPos": 54,
        "value": 10.76923076923077
    },
    {
        "id": "layerzero_listing",
        "name": "LayerZero Listing",
        "price": 10000,
        "profitPerHour": 900,
        "condition": null,
        "section": "Markets",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 900,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 10000,
        "startCurrentProfitPerHour": 900,
        "startPos": 55,
        "value": 11.11111111111111
    },
    {
        "id": "kyc",
        "name": "KYC",
        "price": 100,
        "image": "kyc.svg",
        "profitPerHour": 10,
        "condition": null,
        "section": "Legal",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 10,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 100,
        "startCurrentProfitPerHour": 10,
        "startPos": 56,
        "value": 10
    },
    {
        "id": "kyb",
        "name": "KYB",
        "price": 500,
        "image": "kyb.svg",
        "profitPerHour": 60,
        "condition": null,
        "section": "Legal",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 60,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 500,
        "startCurrentProfitPerHour": 60,
        "startPos": 57,
        "value": 8.333333333333334
    },
    {
        "id": "legal_opinion",
        "name": "Legal opinion",
        "price": 1000,
        "image": "legal_opinion.svg",
        "profitPerHour": 60,
        "condition": null,
        "section": "Legal",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 60,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 1000,
        "startCurrentProfitPerHour": 60,
        "startPos": 58,
        "value": 16.666666666666668
    },
    {
        "id": "sec_transparancy",
        "name": "SEC transparancy",
        "price": 1200,
        "profitPerHour": 60,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "legal_opinion",
            "level": 5
        },
        "section": "Legal",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 60,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 1200,
        "startCurrentProfitPerHour": 60,
        "startPos": 59,
        "value": 20
    },
    {
        "id": "anti_money_loundering",
        "name": "Anti money loundering",
        "price": 3000,
        "image": "anti_money_loundering.svg",
        "profitPerHour": 280,
        "condition": null,
        "section": "Legal",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 280,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 3000,
        "startCurrentProfitPerHour": 280,
        "startPos": 60,
        "value": 10.714285714285714
    },
    {
        "id": "licence_uae",
        "name": "Licence UAE",
        "price": 5000,
        "profitPerHour": 560,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "kyc",
            "level": 5
        },
        "section": "Legal",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 560,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 5000,
        "startCurrentProfitPerHour": 560,
        "startPos": 61,
        "value": 8.928571428571429
    },
    {
        "id": "licence_europe",
        "name": "Licence Europe",
        "price": 5000,
        "profitPerHour": 720,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "kyc",
            "level": 5
        },
        "section": "Legal",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 720,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 5000,
        "startCurrentProfitPerHour": 720,
        "startPos": 62,
        "value": 6.944444444444445
    },
    {
        "id": "licence_asia",
        "name": "Licence Asia",
        "price": 5000,
        "profitPerHour": 370,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "kyc",
            "level": 5
        },
        "section": "Legal",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 370,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 5000,
        "startCurrentProfitPerHour": 370,
        "startPos": 63,
        "value": 13.513513513513514
    },
    {
        "id": "licence_south_america",
        "name": "Licence South America",
        "price": 5000,
        "profitPerHour": 390,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "kyc",
            "level": 5
        },
        "section": "Legal",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 390,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 5000,
        "startCurrentProfitPerHour": 390,
        "startPos": 64,
        "value": 12.820512820512821
    },
    {
        "id": "licence_australia",
        "name": "Licence Australia",
        "price": 5000,
        "profitPerHour": 680,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "kyc",
            "level": 5
        },
        "section": "Legal",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 680,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 5000,
        "startCurrentProfitPerHour": 680,
        "startPos": 65,
        "value": 7.352941176470588
    },
    {
        "id": "licence_north_america",
        "name": "Licence North America",
        "price": 10000,
        "profitPerHour": 960,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "sec_transparancy",
            "level": 10
        },
        "section": "Legal",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 960,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 10000,
        "startCurrentProfitPerHour": 960,
        "startPos": 66,
        "value": 10.416666666666666
    },
    {
        "id": "licence_nigeria",
        "name": "Licence Nigeria",
        "price": 1500,
        "profitPerHour": 170,
        "condition": null,
        "section": "Legal",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 170,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 1500,
        "startCurrentProfitPerHour": 170,
        "startPos": 67,
        "value": 8.823529411764707
    },
    {
        "id": "licence_japan",
        "name": "Licence Japan",
        "price": 50000,
        "profitPerHour": 2600,
        "condition": {
            "_type": "MoreReferralsCount",
            "moreReferralsCount": 1
        },
        "section": "Legal",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 2600,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 50000,
        "startCurrentProfitPerHour": 2600,
        "startPos": 68,
        "value": 19.23076923076923
    },
    {
        "id": "licence_ethiopia",
        "name": "Licence Ethiopia",
        "price": 35000,
        "profitPerHour": 1800,
        "condition": {
            "_type": "ReferralCount",
            "referralCount": 2
        },
        "section": "Legal",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 1800,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 35000,
        "startCurrentProfitPerHour": 1800,
        "startPos": 69,
        "value": 19.444444444444443
    },
    {
        "id": "licence_india",
        "name": "Licence India",
        "price": 45000,
        "profitPerHour": 2500,
        "condition": {
            "_type": "ReferralCount",
            "referralCount": 3
        },
        "section": "Legal",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 2500,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 45000,
        "startCurrentProfitPerHour": 2500,
        "startPos": 70,
        "value": 18
    },
    {
        "id": "licence_bangladesh",
        "name": "Licence Bangladesh",
        "price": 70000,
        "profitPerHour": 3500,
        "condition": {
            "_type": "ReferralCount",
            "referralCount": 4
        },
        "section": "Legal",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 3500,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 70000,
        "startCurrentProfitPerHour": 3500,
        "startPos": 71,
        "value": 20
    },
    {
        "id": "licence_indonesia",
        "name": "Licence Indonesia",
        "price": 100000,
        "profitPerHour": 5000,
        "condition": {
            "_type": "ReferralCount",
            "referralCount": 4
        },
        "section": "Legal",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 5000,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 100000,
        "startCurrentProfitPerHour": 5000,
        "startPos": 72,
        "value": 20
    },
    {
        "id": "licence_vietnam",
        "name": "Licence Vietnam",
        "releaseAt": "2024-06-23T11:00:00.000Z",
        "price": 85000,
        "profitPerHour": 4000,
        "condition": {
            "_type": "MoreReferralsCount",
            "moreReferralsCount": 1
        },
        "section": "Legal",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 4000,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 85000,
        "startCurrentProfitPerHour": 4000,
        "startPos": 73,
        "value": 21.25
    },
    {
        "id": "licence_turkey",
        "name": "Licence Turkey",
        "releaseAt": "2024-06-25T11:00:00.000Z",
        "price": 75000,
        "profitPerHour": 3000,
        "condition": {
            "_type": "MoreReferralsCount",
            "moreReferralsCount": 1
        },
        "section": "Legal",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 3000,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 75000,
        "startCurrentProfitPerHour": 3000,
        "startPos": 74,
        "value": 25
    },
    {
        "id": "licence_philippines",
        "name": "Licence Philippines",
        "releaseAt": "2024-06-27T11:00:00.000Z",
        "price": 150000,
        "profitPerHour": 6500,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "top10_global",
            "level": 3
        },
        "section": "Legal",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 6500,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 150000,
        "startCurrentProfitPerHour": 6500,
        "startPos": 75,
        "value": 23.076923076923077
    },
    {
        "id": "dex",
        "name": "DEX",
        "releaseAt": "2024-07-09T11:00:00.000Z",
        "price": 75000,
        "profitPerHour": 3000,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "btc_pairs",
            "level": 10
        },
        "section": "Web3",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 3000,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 75000,
        "startCurrentProfitPerHour": 3000,
        "startPos": 76,
        "value": 25
    },
    {
        "id": "oracle",
        "name": "Oracle",
        "releaseAt": "2024-07-10T11:00:00.000Z",
        "price": 17500,
        "profitPerHour": 800,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "web3_integration",
            "level": 5
        },
        "section": "Web3",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 800,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 17500,
        "startCurrentProfitPerHour": 800,
        "startPos": 77,
        "value": 21.875
    },
    {
        "id": "vesting_smartcontracts",
        "name": "Vesting Smartcontracts",
        "releaseAt": "2024-07-11T11:00:00.000Z",
        "price": 41000,
        "profitPerHour": 1200,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "web3_integration",
            "level": 7
        },
        "section": "Web3",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 1200,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 41000,
        "startCurrentProfitPerHour": 1200,
        "startPos": 78,
        "value": 34.166666666666664
    },
    {
        "id": "launchpad",
        "name": "Launchpad",
        "releaseAt": "2024-07-12T11:00:00.000Z",
        "price": 95000,
        "profitPerHour": 3000,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "vc_labs",
            "level": 15
        },
        "section": "Web3",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 3000,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 95000,
        "startCurrentProfitPerHour": 3000,
        "startPos": 79,
        "value": 31.666666666666668
    },
    {
        "id": "nft_marketplace",
        "name": "NFT Marketplace",
        "releaseAt": "2024-07-13T11:00:00.000Z",
        "price": 78000,
        "profitPerHour": 2000,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "nft_collection_launch",
            "level": 5
        },
        "section": "Web3",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 2000,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 78000,
        "startCurrentProfitPerHour": 2000,
        "startPos": 80,
        "value": 39
    },
    {
        "id": "grant_developers",
        "name": "Grant for Developers",
        "releaseAt": "2024-07-28T11:00:00.000Z",
        "price": 100000,
        "profitPerHour": 4000,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "product_team",
            "level": 10
        },
        "section": "Web3",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 4000,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 100000,
        "startCurrentProfitPerHour": 4000,
        "startPos": 81,
        "value": 25
    },
    {
        "id": "nft_metaverse",
        "name": "NFT Metaverse",
        "releaseAt": "2024-07-29T11:00:00.000Z",
        "price": 500000,
        "profitPerHour": 2000,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "x",
            "level": 7
        },
        "section": "Web3",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 2000,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 500000,
        "startCurrentProfitPerHour": 2000,
        "startPos": 82,
        "value": 250
    },
    {
        "id": "crypto_farming",
        "name": "Crypto Farming",
        "releaseAt": "2024-07-30T11:00:00.000Z",
        "price": 150000,
        "profitPerHour": 3000,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "youtube",
            "level": 8
        },
        "section": "Web3",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 3000,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 150000,
        "startCurrentProfitPerHour": 3000,
        "startPos": 83,
        "value": 50
    },
    {
        "id": "sport_marketplace",
        "name": "Sport Collectibles Marketplace",
        "releaseAt": "2024-07-31T11:00:00.000Z",
        "price": 15000,
        "profitPerHour": 700,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "fan_tokens",
            "level": 10
        },
        "section": "Web3",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 700,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 15000,
        "startCurrentProfitPerHour": 700,
        "startPos": 84,
        "value": 21.428571428571427
    },
    {
        "id": "market_making",
        "name": "Market Making",
        "releaseAt": "2024-08-01T11:00:00.000Z",
        "price": 17000,
        "profitPerHour": 600,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "prediction_markets",
            "level": 12
        },
        "section": "Web3",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 600,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 17000,
        "startCurrentProfitPerHour": 600,
        "startPos": 85,
        "value": 28.333333333333332
    },
    {
        "id": "web3_advertising",
        "name": "Web3 Advertising Platform",
        "releaseAt": "2024-08-02T11:00:00.000Z",
        "price": 13000,
        "profitPerHour": 400,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "influencers",
            "level": 10
        },
        "section": "Web3",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 400,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 13000,
        "startCurrentProfitPerHour": 400,
        "startPos": 86,
        "value": 32.5
    },
    {
        "id": "sports_integration",
        "name": "Sports integration",
        "expiresAt": "2024-07-02T09:00:00.000Z",
        "price": 35000,
        "profitPerHour": 3000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 3000,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 35000,
        "startCurrentProfitPerHour": 3000,
        "startPos": 87,
        "value": 11.666666666666666
    },
    {
        "id": "sports_integration_0207",
        "name": "Sports integration",
        "expiresAt": "2024-07-03T09:00:00.000Z",
        "price": 35000,
        "profitPerHour": 3000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 3000,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 35000,
        "startCurrentProfitPerHour": 3000,
        "startPos": 88,
        "value": 11.666666666666666
    },
    {
        "id": "sports_integration_0507",
        "name": "Sports integration",
        "expiresAt": "2024-07-05T09:00:00.000Z",
        "price": 35000,
        "profitPerHour": 3000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 3000,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 35000,
        "startCurrentProfitPerHour": 3000,
        "startPos": 89,
        "value": 11.666666666666666
    },
    {
        "id": "riyadh_masters_2024",
        "name": "Riyadh Masters 2024",
        "expiresAt": "2024-07-05T09:00:00.000Z",
        "price": 35000,
        "profitPerHour": 3000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 3000,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 35000,
        "startCurrentProfitPerHour": 3000,
        "startPos": 90,
        "value": 11.666666666666666
    },
    {
        "id": "sports_integration_0607",
        "name": "Quaterfinals are coming",
        "expiresAt": "2024-07-06T09:00:00.000Z",
        "price": 35000,
        "profitPerHour": 3000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 3000,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 35000,
        "startCurrentProfitPerHour": 3000,
        "startPos": 91,
        "value": 11.666666666666666
    },
    {
        "id": "sports_integration_0707",
        "name": "Quaterfinals are coming",
        "releaseAt": "2024-07-06T09:00:00.000Z",
        "expiresAt": "2024-07-07T09:00:00.000Z",
        "price": 35000,
        "profitPerHour": 3000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 3000,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 35000,
        "startCurrentProfitPerHour": 3000,
        "startPos": 92,
        "value": 11.666666666666666
    },
    {
        "id": "sports_integration_0807",
        "name": "Only 4 best left",
        "releaseAt": "2024-07-07T09:00:00.000Z",
        "expiresAt": "2024-07-09T09:00:00.000Z",
        "price": 35000,
        "profitPerHour": 3000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 3000,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 35000,
        "startCurrentProfitPerHour": 3000,
        "startPos": 93,
        "value": 11.666666666666666
    },
    {
        "id": "sports_integration_0907",
        "name": "Semi-final Spain vs France",
        "releaseAt": "2024-07-09T09:00:00.000Z",
        "expiresAt": "2024-07-10T09:00:00.000Z",
        "price": 35000,
        "profitPerHour": 3000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 3000,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 35000,
        "startCurrentProfitPerHour": 3000,
        "startPos": 94,
        "value": 11.666666666666666
    },
    {
        "id": "sports_integration_1007",
        "name": "Semi-final England vs Netherlands",
        "releaseAt": "2024-07-10T09:00:00.000Z",
        "expiresAt": "2024-07-11T09:00:00.000Z",
        "price": 35000,
        "profitPerHour": 3000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 3000,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 35000,
        "startCurrentProfitPerHour": 3000,
        "startPos": 95,
        "value": 11.666666666666666
    },
    {
        "id": "sports_integration_1407",
        "name": "Final England vs Spain",
        "releaseAt": "2024-07-14T09:30:00.000Z",
        "expiresAt": "2024-07-15T04:00:00.000Z",
        "price": 35000,
        "profitPerHour": 3000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 3000,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 35000,
        "startCurrentProfitPerHour": 3000,
        "startPos": 96,
        "value": 11.666666666666666
    },
    {
        "id": "usdt_on_ton",
        "name": "USDT on TON",
        "price": 10000,
        "image": "usdt_on_ton.svg",
        "profitPerHour": 1350,
        "condition": {
            "_type": "ReferralCount",
            "referralCount": 3
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 1350,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 10000,
        "startCurrentProfitPerHour": 1350,
        "startPos": 97,
        "value": 7.407407407407407
    },
    {
        "id": "blockchain_life_2024",
        "name": "Blockchain Life 2024",
        "expiresAt": "2024-04-17T15:00:00.000Z",
        "price": 200000,
        "image": "blockchain_life_2024.svg",
        "profitPerHour": 14000,
        "condition": {
            "_type": "ReferralCount",
            "referralCount": 5
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 14000,
        "isAvailable": false,
        "isExpired": true,
        "startCost": 200000,
        "startCurrentProfitPerHour": 14000,
        "startPos": 98,
        "value": 14.285714285714286
    },
    {
        "id": "token2049",
        "name": "Token2049",
        "expiresAt": "2024-04-23T15:00:00.000Z",
        "price": 100000,
        "image": "token2049.svg",
        "profitPerHour": 1500,
        "condition": {
            "_type": "ReferralCount",
            "referralCount": 7
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 1500,
        "isAvailable": false,
        "isExpired": true,
        "startCost": 100000,
        "startCurrentProfitPerHour": 1500,
        "startPos": 99,
        "value": 66.66666666666667
    },
    {
        "id": "bogdanoff",
        "name": "Bogdanoff is calling",
        "price": 5000,
        "profitPerHour": 475,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "margin_trading_x50",
            "level": 15
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 475,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 5000,
        "startCurrentProfitPerHour": 475,
        "startPos": 100,
        "value": 10.526315789473685
    },
    {
        "id": "apps_center_listing",
        "name": "Apps Center Listing",
        "price": 15000,
        "profitPerHour": 1000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 1000,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 15000,
        "startCurrentProfitPerHour": 1000,
        "startPos": 101,
        "value": 15
    },
    {
        "id": "villa_for_dev_team",
        "name": "Villa for the DEV team",
        "price": 2000,
        "profitPerHour": 450,
        "condition": {
            "_type": "ReferralCount",
            "referralCount": 5
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 450,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 2000,
        "startCurrentProfitPerHour": 450,
        "startPos": 102,
        "value": 4.444444444444445
    },
    {
        "id": "long_squeeze",
        "name": "Long squeeze",
        "price": 30000,
        "image": "long_squeeze.svg",
        "profitPerHour": 2000,
        "condition": {
            "_type": "ReferralCount",
            "referralCount": 9
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 2000,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 30000,
        "startCurrentProfitPerHour": 2000,
        "startPos": 103,
        "value": 15
    },
    {
        "id": "two_chairs",
        "name": "There are two chairs...",
        "price": 50000,
        "profitPerHour": 2000,
        "condition": {
            "_type": "MoreReferralsCount",
            "moreReferralsCount": 1
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 2000,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 50000,
        "startCurrentProfitPerHour": 2000,
        "startPos": 104,
        "value": 25
    },
    {
        "id": "short_squeeze",
        "name": "Short squeeze",
        "price": 35000,
        "image": "short_squeeze.svg",
        "profitPerHour": 1000,
        "condition": {
            "_type": "MoreReferralsCount",
            "moreReferralsCount": 3
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 1000,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 35000,
        "startCurrentProfitPerHour": 1000,
        "startPos": 105,
        "value": 35
    },
    {
        "id": "special_hamster_conference",
        "name": "Special Hamster Conference",
        "price": 5000,
        "profitPerHour": 900,
        "condition": {
            "_type": "SubscribeTelegramChannel",
            "link": "https://t.me/+kK14mIuJR2hlMmNi",
            "channelId": -1002075341442
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 900,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 5000,
        "startCurrentProfitPerHour": 900,
        "startPos": 106,
        "value": 5.555555555555555
    },
    {
        "id": "contract_with_football_club",
        "name": "Ad contract with a football club",
        "expiresAt": "2024-06-01T16:00:00.000Z",
        "price": 25000,
        "profitPerHour": 1750,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "fan_tokens",
            "level": 8
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 1750,
        "isAvailable": false,
        "isExpired": true,
        "startCost": 25000,
        "startCurrentProfitPerHour": 1750,
        "startPos": 107,
        "value": 14.285714285714286
    },
    {
        "id": "venom_blockchain",
        "name": "Venom Blockchain",
        "expiresAt": "2024-05-22T15:00:00.000Z",
        "price": 15000,
        "profitPerHour": 1550,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 1550,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 15000,
        "startCurrentProfitPerHour": 1550,
        "startPos": 108,
        "value": 9.67741935483871
    },
    {
        "id": "notcoin_listing",
        "name": "Notcoin listing",
        "expiresAt": "2024-05-19T12:00:00.000Z",
        "price": 20000,
        "profitPerHour": 2400,
        "condition": {
            "_type": "MoreReferralsCount",
            "moreReferralsCount": 1
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 2400,
        "isAvailable": false,
        "isExpired": true,
        "startCost": 20000,
        "startCurrentProfitPerHour": 2400,
        "startPos": 109,
        "value": 8.333333333333334
    },
    {
        "id": "hamster_ai",
        "name": "Hamster AI",
        "expiresAt": "2024-05-21T15:00:00.000Z",
        "price": 3700,
        "profitPerHour": 650,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "x",
            "level": 3
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 650,
        "isAvailable": false,
        "isExpired": true,
        "startCost": 3700,
        "startCurrentProfitPerHour": 650,
        "startPos": 110,
        "value": 5.6923076923076925
    },
    {
        "id": "nft_collection_launch",
        "name": "NFT Collection Launch",
        "price": 17000,
        "profitPerHour": 1200,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "margin_trading_x100",
            "level": 10
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 1200,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 17000,
        "startCurrentProfitPerHour": 1200,
        "startPos": 111,
        "value": 14.166666666666666
    },
    {
        "id": "top10_global",
        "name": "Top 10 Global Ranking",
        "price": 10000,
        "profitPerHour": 1200,
        "condition": {
            "_type": "SubscribeTelegramChannel",
            "link": "https://t.me/+_uqfAor-9TFkOWNi",
            "channelId": -1002075341442
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 1200,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 10000,
        "startCurrentProfitPerHour": 1200,
        "startPos": 112,
        "value": 8.333333333333334
    },
    {
        "id": "bitcoin_pizza_day",
        "name": "Bitcoin Pizza Day",
        "price": 1000,
        "profitPerHour": 100,
        "condition": {
            "_type": "SubscribeTelegramChannel",
            "link": "https://t.me/+BKxnK5qrA7JhN2Uy",
            "channelId": -1002075341442
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 100,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 1000,
        "startCurrentProfitPerHour": 100,
        "startPos": 113,
        "value": 10
    },
    {
        "id": "ceo_21m",
        "name": "21,000,000 CEOs",
        "expiresAt": "2024-05-25T12:00:00.000Z",
        "price": 2500,
        "profitPerHour": 300,
        "condition": {
            "_type": "MoreReferralsCount",
            "moreReferralsCount": 1
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 300,
        "isAvailable": false,
        "isExpired": true,
        "startCost": 2500,
        "startCurrentProfitPerHour": 300,
        "startPos": 114,
        "value": 8.333333333333334
    },
    {
        "id": "hamster_daily_show",
        "name": "Hamster daily show",
        "expiresAt": "2024-06-01T16:00:00.000Z",
        "price": 2000,
        "profitPerHour": 200,
        "condition": {
            "_type": "LinkWithoutCheck",
            "link": "http://twitter.com/hamster_kombat"
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 200,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 2000,
        "startCurrentProfitPerHour": 200,
        "startPos": 115,
        "value": 10
    },
    {
        "id": "hamster_youtube_channel",
        "name": "Hamster YouTube Channel",
        "price": 1500,
        "profitPerHour": 250,
        "condition": {
            "_type": "LinkWithoutCheck",
            "link": "https://youtube.com/@hamsterkombat_official"
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 250,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 1500,
        "startCurrentProfitPerHour": 250,
        "startPos": 116,
        "value": 6
    },
    {
        "id": "hamster_youtube_gold_button",
        "name": "YouTube Gold Button",
        "price": 2500,
        "profitPerHour": 275,
        "condition": {
            "_type": "LinksToUpgradeLevel",
            "subscribeLink": "https://www.youtube.com/@HamsterKombat_Official?sub_confirmation=1",
            "links": [
                "https://www.youtube.com/shorts/FW-GpTr-FcU",
                "https://www.youtube.com/shorts/a_gHYwMsjh0",
                "https://www.youtube.com/shorts/bISprviSSxg",
                "https://www.youtube.com/shorts/S9_T6LokFNc",
                "https://www.youtube.com/shorts/uefHXh7Dvms",
                "https://www.youtube.com/shorts/825u1acydv4"
            ]
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 275,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 2500,
        "startCurrentProfitPerHour": 275,
        "startPos": 117,
        "value": 9.090909090909092
    },
    {
        "id": "web3_academy_launch",
        "name": "Web3 academy launch",
        "price": 11000,
        "profitPerHour": 1500,
        "condition": {
            "_type": "LinksToUpgradeLevel",
            "subscribeLink": "https://www.youtube.com/@HamsterKombat_Official?sub_confirmation=1",
            "links": [
                "https://www.youtube.com/shorts/Sg437HhohRQ",
                "https://www.youtube.com/shorts/JL6ljxjN74w",
                "https://www.youtube.com/shorts/59aBxaH3pT0",
                "https://www.youtube.com/shorts/_pnavaIStX0",
                "https://www.youtube.com/shorts/Ut6xIBjyRhI",
                "https://www.youtube.com/shorts/PZp9eGzwI70",
                "https://www.youtube.com/shorts/FW-GpTr-FcU",
                "https://www.youtube.com/shorts/a_gHYwMsjh0"
            ]
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 1500,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 11000,
        "startCurrentProfitPerHour": 1500,
        "startPos": 118,
        "value": 7.333333333333333
    },
    {
        "id": "consensys_piranja_pass",
        "name": "Consensus Piranha Pass",
        "price": 50000,
        "profitPerHour": 1900,
        "condition": {
            "_type": "SubscribeTelegramChannel",
            "link": "https://t.me/+e52PfDAw_w1lMzNi",
            "channelId": -1002075341442
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 1900,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 50000,
        "startCurrentProfitPerHour": 1900,
        "startPos": 119,
        "value": 26.31578947368421
    },
    {
        "id": "partner_announce",
        "name": "TON + Hamster Kombat = Success",
        "price": 1000000,
        "profitPerHour": 5000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 5000,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 1000000,
        "startCurrentProfitPerHour": 5000,
        "startPos": 120,
        "value": 200
    },
    {
        "id": "hamster_drop",
        "name": "Hamster Kombat merch",
        "price": 3000,
        "profitPerHour": 100,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 100,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 3000,
        "startCurrentProfitPerHour": 100,
        "startPos": 121,
        "value": 30
    },
    {
        "id": "premarket_launch",
        "name": "Premarket Launch",
        "price": 1000000,
        "profitPerHour": 7500,
        "condition": {
            "_type": "MoreReferralsCount",
            "moreReferralsCount": 1
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 7500,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 1000000,
        "startCurrentProfitPerHour": 7500,
        "startPos": 122,
        "value": 133.33333333333334
    },
    {
        "id": "tg_leaders",
        "name": "TG Leaders",
        "price": 22000,
        "profitPerHour": 2300,
        "condition": {
            "_type": "SubscribeTelegramChannel",
            "link": "https://t.me/+e52PfDAw_w1lMzNi",
            "channelId": -1002075341442
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 2300,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 22000,
        "startCurrentProfitPerHour": 2300,
        "startPos": 123,
        "value": 9.565217391304348
    },
    {
        "id": "youtube_25_million",
        "name": "YouTube 25 Million",
        "releaseAt": "2024-06-22T11:00:00.000Z",
        "price": 18000,
        "profitPerHour": 2100,
        "condition": {
            "_type": "LinkWithoutCheck",
            "link": "https://youtube.com/@hamsterkombat_official"
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 2100,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 18000,
        "startCurrentProfitPerHour": 2100,
        "startPos": 124,
        "value": 8.571428571428571
    },
    {
        "id": "hamster_green_energy",
        "name": "Hamster Green energy",
        "releaseAt": "2024-06-24T11:00:00.000Z",
        "price": 17000,
        "profitPerHour": 2000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 2000,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 17000,
        "startCurrentProfitPerHour": 2000,
        "startPos": 125,
        "value": 8.5
    },
    {
        "id": "twitter_10_million",
        "name": "X Network 10 Million",
        "releaseAt": "2024-06-26T11:00:00.000Z",
        "price": 7000,
        "profitPerHour": 400,
        "condition": {
            "_type": "LinkWithoutCheck",
            "link": "http://twitter.com/hamster_kombat"
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 400,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 7000,
        "startCurrentProfitPerHour": 400,
        "startPos": 126,
        "value": 17.5
    },
    {
        "id": "web3_game_con",
        "name": "Web3 Game Con",
        "expiresAt": "2024-07-10T13:00:00.000Z",
        "price": 30000,
        "profitPerHour": 1200,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 1200,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 30000,
        "startCurrentProfitPerHour": 1200,
        "startPos": 127,
        "value": 25
    },
    {
        "id": "hamster_break_records",
        "name": "Hamsters break records",
        "price": 500000,
        "profitPerHour": 2750,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "tg_leaders",
            "level": 1
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 2750,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 500000,
        "startCurrentProfitPerHour": 2750,
        "startPos": 128,
        "value": 181.8181818181818
    },
    {
        "id": "cx_hub_istanbul",
        "name": "CX Hub Istanbul",
        "releaseAt": "2024-07-03T14:00:00.000Z",
        "price": 55000,
        "profitPerHour": 3000,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "support_team",
            "level": 12
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 3000,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 55000,
        "startCurrentProfitPerHour": 3000,
        "startPos": 129,
        "value": 18.333333333333332
    },
    {
        "id": "adv_integration_0907",
        "name": "Percussion taps",
        "expiresAt": "2024-07-13T09:00:00.000Z",
        "price": 20000,
        "profitPerHour": 1500,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 1500,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 20000,
        "startCurrentProfitPerHour": 1500,
        "startPos": 130,
        "value": 13.333333333333334
    },
    {
        "id": "adv_integration_1307",
        "name": "250M Hamster players",
        "releaseAt": "2024-07-13T09:00:00.000Z",
        "expiresAt": "2024-07-17T11:50:00.000Z",
        "price": 20000,
        "profitPerHour": 1500,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 1500,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 20000,
        "startCurrentProfitPerHour": 1500,
        "startPos": 131,
        "value": 13.333333333333334
    },
    {
        "id": "business_jet",
        "name": "Business jet",
        "releaseAt": "2024-07-14T11:00:00.000Z",
        "price": 12000000,
        "profitPerHour": 3000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 3000,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 12000000,
        "startCurrentProfitPerHour": 3000,
        "startPos": 132,
        "value": 4000
    },
    {
        "id": "call_btc_rise",
        "name": "Call for BTC to rise",
        "releaseAt": "2024-07-15T11:00:00.000Z",
        "price": 5000000,
        "profitPerHour": 5000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 5000,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 5000000,
        "startCurrentProfitPerHour": 5000,
        "startPos": 133,
        "value": 1000
    },
    {
        "id": "rolex_soulmate",
        "name": "HamsterWatch for soulmate",
        "releaseAt": "2024-07-16T11:00:00.000Z",
        "price": 1000000,
        "profitPerHour": 1000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 1000,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 1000000,
        "startCurrentProfitPerHour": 1000,
        "startPos": 134,
        "value": 1000
    },
    {
        "id": "appstore_launch",
        "name": "HamsterStore launch",
        "releaseAt": "2024-07-17T11:00:00.000Z",
        "price": 95000,
        "profitPerHour": 5000,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "it_team",
            "level": 15
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 5000,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 95000,
        "startCurrentProfitPerHour": 5000,
        "startPos": 135,
        "value": 19
    },
    {
        "id": "fight_fight",
        "name": "Fight fight fight",
        "expiresAt": "2024-07-24T11:00:00.000Z",
        "price": 1500000,
        "profitPerHour": 10000,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "ceo",
            "level": 17
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 10000,
        "isAvailable": false,
        "isExpired": true,
        "startCost": 1500000,
        "startCurrentProfitPerHour": 10000,
        "startPos": 136,
        "value": 150
    },
    {
        "id": "telegram_50m",
        "name": "50M Telegram channel",
        "releaseAt": "2024-07-18T11:00:00.000Z",
        "price": 50000,
        "profitPerHour": 1000,
        "condition": {
            "_type": "SubscribeTelegramChannel",
            "link": "https://t.me/+e52PfDAw_w1lMzNi",
            "channelId": -1002075341442
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 1000,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 50000,
        "startCurrentProfitPerHour": 1000,
        "startPos": 137,
        "value": 50
    },
    {
        "id": "google_analytics",
        "name": "Hamster Analytics",
        "releaseAt": "2024-07-19T11:00:00.000Z",
        "price": 75000,
        "profitPerHour": 2000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 2000,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 75000,
        "startCurrentProfitPerHour": 2000,
        "startPos": 138,
        "value": 37.5
    },
    {
        "id": "session_australia",
        "name": "Strategic session in Australia",
        "releaseAt": "2024-07-20T09:00:00.000Z",
        "expiresAt": "2024-07-22T09:00:00.000Z",
        "price": 100000,
        "profitPerHour": 3500,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 3500,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 100000,
        "startCurrentProfitPerHour": 3500,
        "startPos": 139,
        "value": 28.571428571428573
    },
    {
        "id": "telegram_miniapp_launch",
        "name": "Telegram Miniapp Launch",
        "releaseAt": "2024-07-24T11:00:00.000Z",
        "price": 25000,
        "profitPerHour": 1000,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "it_team",
            "level": 15
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 1000,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 25000,
        "startCurrentProfitPerHour": 1000,
        "startPos": 140,
        "value": 25
    },
    {
        "id": "telegram_stars_integration",
        "name": "Telegram Stars integration",
        "releaseAt": "2024-07-25T11:00:00.000Z",
        "price": 17000,
        "profitPerHour": 800,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "it_team",
            "level": 16
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 800,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 17000,
        "startCurrentProfitPerHour": 800,
        "startPos": 141,
        "value": 21.25
    },
    {
        "id": "hamsterbank",
        "name": "HamsterBank",
        "releaseAt": "2024-07-27T11:00:00.000Z",
        "price": 300000,
        "profitPerHour": 19000,
        "condition": {
            "_type": "ReferralCount",
            "referralCount": 10
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 19000,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 300000,
        "startCurrentProfitPerHour": 19000,
        "startPos": 142,
        "value": 15.789473684210526
    },
    {
        "id": "kamala_calling",
        "name": "Kamala is calling",
        "releaseAt": "2024-07-24T11:00:00.000Z",
        "expiresAt": "2024-07-31T11:00:00.000Z",
        "price": 50000,
        "profitPerHour": 3500,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 3500,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 50000,
        "startCurrentProfitPerHour": 3500,
        "startPos": 143,
        "value": 14.285714285714286
    },
    {
        "id": "bitcoin_conference_2024",
        "name": "Bitcoin Conference 2024",
        "releaseAt": "2024-07-25T11:00:00.000Z",
        "expiresAt": "2024-08-01T11:00:00.000Z",
        "price": 60000,
        "profitPerHour": 2900,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 2900,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 60000,
        "startCurrentProfitPerHour": 2900,
        "startPos": 144,
        "value": 20.689655172413794
    },
    {
        "id": "adv_integration_2607",
        "name": "The water is clear",
        "releaseAt": "2024-07-26T11:00:00.000Z",
        "expiresAt": "2024-07-28T04:00:00.000Z",
        "price": 35000,
        "profitPerHour": 3000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 3000,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 35000,
        "startCurrentProfitPerHour": 3000,
        "startPos": 145,
        "value": 11.666666666666666
    },
    {
        "id": "welcome_to_ogames",
        "name": "Carry it like it’s hot",
        "releaseAt": "2024-07-26T11:00:00.000Z",
        "expiresAt": "2024-08-02T17:30:00.000Z",
        "price": 50000,
        "profitPerHour": 2000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 2000,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 50000,
        "startCurrentProfitPerHour": 2000,
        "startPos": 146,
        "value": 25
    },
    {
        "id": "ethereum_bd",
        "name": "Ethereum birthday",
        "releaseAt": "2024-07-30T11:00:00.000Z",
        "expiresAt": "2024-08-06T11:00:00.000Z",
        "price": 90000,
        "profitPerHour": 2500,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 2500,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 90000,
        "startCurrentProfitPerHour": 2500,
        "startPos": 147,
        "value": 36
    },
    {
        "id": "adv_integration_3107",
        "name": "This is fine",
        "releaseAt": "2024-07-31T11:00:00.000Z",
        "expiresAt": "2024-08-02T11:00:00.000Z",
        "price": 35000,
        "profitPerHour": 3000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 3000,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 35000,
        "startCurrentProfitPerHour": 3000,
        "startPos": 148,
        "value": 11.666666666666666
    },
    {
        "id": "adv_integration_0308",
        "name": "Games in Paris",
        "expiresAt": "2024-08-06T20:59:00.000Z",
        "price": 35000,
        "image": "adv_integration_0308.png",
        "profitPerHour": 3000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 3000,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 35000,
        "startCurrentProfitPerHour": 3000,
        "startPos": 149,
        "value": 11.666666666666666
    },
    {
        "id": "hamstergpt",
        "name": "HamsterGPT",
        "releaseAt": "2024-08-03T11:00:00.000Z",
        "price": 55000,
        "profitPerHour": 1800,
        "condition": {
            "_type": "ByUpgrade",
            "upgradeId": "security_team",
            "level": 15
        },
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 1800,
        "isAvailable": false,
        "isExpired": false,
        "startCost": 55000,
        "startCurrentProfitPerHour": 1800,
        "startPos": 150,
        "value": 30.555555555555557
    },
    {
        "id": "sleeping_hamster",
        "name": "Sleeping hamster",
        "releaseAt": "2024-08-05T11:00:00.000Z",
        "price": 15000,
        "profitPerHour": 600,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 600,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 15000,
        "startCurrentProfitPerHour": 600,
        "startPos": 151,
        "value": 25
    },
    {
        "id": "healthy_hamster",
        "name": "Healthy nutrition hamster",
        "releaseAt": "2024-08-06T11:00:00.000Z",
        "price": 17000,
        "profitPerHour": 800,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 800,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 17000,
        "startCurrentProfitPerHour": 800,
        "startPos": 152,
        "value": 21.25
    },
    {
        "id": "gym_hamster",
        "name": "Gym hamster",
        "toggle": {
            "enableAt": "2024-08-07T11:00:00.000Z"
        },
        "price": 12000,
        "profitPerHour": 500,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 500,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 12000,
        "startCurrentProfitPerHour": 500,
        "startPos": 153,
        "value": 24
    },
    {
        "id": "ton_listing",
        "name": "TON listing on Binance",
        "toggle": {
            "enableAt": "2024-08-08T10:00:00.000Z"
        },
        "expiresAt": "2024-08-15T10:00:00.000Z",
        "price": 90000,
        "profitPerHour": 2500,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 2500,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 90000,
        "startCurrentProfitPerHour": 2500,
        "startPos": 154,
        "value": 36
    },
    {
        "id": "university_hamster",
        "name": "University hamster",
        "toggle": {
            "enableAt": "2024-08-08T11:00:00.000Z"
        },
        "price": 23000,
        "profitPerHour": 1100,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 1100,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 23000,
        "startCurrentProfitPerHour": 1100,
        "startPos": 155,
        "value": 20.90909090909091
    },
    {
        "id": "vipassana_hamster",
        "name": "Vipassana hamster",
        "toggle": {
            "enableAt": "2024-08-09T11:00:00.000Z"
        },
        "price": 9000,
        "profitPerHour": 600,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 600,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 9000,
        "startCurrentProfitPerHour": 600,
        "startPos": 156,
        "value": 15
    },
    {
        "id": "adv_integration_0908",
        "name": "Finals are approaching",
        "toggle": {
            "enableAt": "2024-08-09T16:33:00.000Z"
        },
        "expiresAt": "2024-08-12T20:00:00.000Z",
        "price": 50000,
        "image": "adv_integration_0908.png",
        "profitPerHour": 4000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 4000,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 50000,
        "startCurrentProfitPerHour": 4000,
        "startPos": 157,
        "value": 12.5
    },
    {
        "id": "hamster_helps_whales",
        "name": "Hamster helps whales",
        "toggle": {
            "enableAt": "2024-08-10T11:00:00.000Z"
        },
        "price": 31000,
        "profitPerHour": 2000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 2000,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 31000,
        "startCurrentProfitPerHour": 2000,
        "startPos": 158,
        "value": 15.5
    },
    {
        "id": "hamster_with_friends",
        "name": "Hamster with friends",
        "toggle": {
            "enableAt": "2024-08-11T11:00:00.000Z"
        },
        "price": 5000,
        "profitPerHour": 300,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 300,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 5000,
        "startCurrentProfitPerHour": 300,
        "startPos": 159,
        "value": 16.666666666666668
    },
    {
        "id": "telegram_11_years",
        "name": "11 years Telegram",
        "expiresAt": "2024-08-21T13:00:00.000Z",
        "price": 111000,
        "profitPerHour": 11000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 11000,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 111000,
        "startCurrentProfitPerHour": 11000,
        "startPos": 160,
        "value": 10.090909090909092
    },
    {
        "id": "adv_integration_1608",
        "name": "Investing in gold",
        "toggle": {
            "enableAt": "2024-08-16T09:00:00.000Z"
        },
        "expiresAt": "2024-08-18T08:59:00.000Z",
        "price": 35000,
        "profitPerHour": 3000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 3000,
        "isAvailable": true,
        "isExpired": true,
        "startCost": 35000,
        "startCurrentProfitPerHour": 3000,
        "startPos": 161,
        "value": 11.666666666666666
    },
    {
        "id": "adv_integration_1908",
        "name": "Energy investments",
        "toggle": {
            "enableAt": "2024-08-19T09:00:00.000Z"
        },
        "expiresAt": "2024-08-26T08:59:00.000Z",
        "price": 150000,
        "profitPerHour": 20000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 20000,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 150000,
        "startCurrentProfitPerHour": 20000,
        "startPos": 162,
        "value": 7.5
    },
    {
        "id": "communication_mentor",
        "name": "Communication with a mentor",
        "toggle": {
            "enableAt": "2024-08-20T11:00:00.000Z"
        },
        "price": 25000,
        "profitPerHour": 1000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 1000,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 25000,
        "startCurrentProfitPerHour": 1000,
        "startPos": 163,
        "value": 25
    },
    {
        "id": "company_planning",
        "name": "Company development planning",
        "toggle": {
            "enableAt": "2024-08-21T11:00:00.000Z"
        },
        "price": 15000,
        "profitPerHour": 800,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 800,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 15000,
        "startCurrentProfitPerHour": 800,
        "startPos": 164,
        "value": 18.75
    },
    {
        "id": "negotiations_partners",
        "name": "Negotiations with partners",
        "toggle": {
            "enableAt": "2024-08-22T11:00:00.000Z"
        },
        "price": 45000,
        "profitPerHour": 2000,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 2000,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 45000,
        "startCurrentProfitPerHour": 2000,
        "startPos": 165,
        "value": 22.5
    },
    {
        "id": "speaking_tv_show",
        "name": "Speaking on a TV show",
        "toggle": {
            "enableAt": "2024-08-23T11:00:00.000Z"
        },
        "price": 20000,
        "profitPerHour": 900,
        "condition": null,
        "section": "Specials",
        "level": 1,
        "currentProfitPerHour": 0,
        "profitPerHourDelta": 900,
        "isAvailable": true,
        "isExpired": false,
        "startCost": 20000,
        "startCurrentProfitPerHour": 900,
        "startPos": 166,
        "value": 22.22222222222222
    }
];
export const COSTCARDCOEFFICIENT = 1.1025;
export const COSTCARDCOEFFICIENTMULT = 1.05;
export const INCOMECARDCOEFFICIENT = 1.07;